[package]
name = "ckb-testtool"
version = "0.1.0"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-always-success-script = "0.0.1"
ckb-tool = { path = "../tool" }
rand = "0.7"

[dev-dependencies]
ckb-system-scripts = "0.5"
