[package]
name = "ckb-testtool"
version = "0.3.0"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"
license = "MIT"
description = "CKB contract testing tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-always-success-script = "0.0.1"
rand = "0.7"
lazy_static = "1.4"
linked_hash_set = "0.1"
ckb-chain-spec = "0.40.0"
ckb-types = "0.40.0"
ckb-error = "0.40.0"
ckb-script = "0.40.0"
ckb-hash = "0.40.0"
ckb-jsonrpc-types = "0.40.0"
ckb-crypto = "0.40.0"
ckb-resource = "0.40.0"
ckb-verification = "0.40.0"
ckb-traits = "0.40.0"
simple-jsonrpc-client = "0.1"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
ckb-system-scripts = "0.5"
