[package]
name = "ckb-tool"
version = "0.1.0"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
ckb-chain-spec = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-error = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-script = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-hash = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-sdk-types = { git = "https://github.com/nervosnetwork/ckb-cli", tag = "v0.26.0" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-crypto = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
ckb-resource = { git = "https://github.com/nervosnetwork/ckb", tag = "v0.26.0-rc2" }
jsonrpc-client = { git = "https://github.com/jjyr/jsonrpc-client", branch = "master" }
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
